node {
   def commit_id
   stage('Preparation') {
     checkout scm
     sh "git rev-parse --short HEAD > .git/commit-id"                        
     commit_id = readFile('.git/commit-id').trim()
   }
   stage('test') {
     nodejs(nodeJSInstallationName: 'Default') {
       sh 'npm install --only=dev'
       sh 'npm test'
     }
   }
   stage('docker build/push') {
     docker.withRegistry(credentialsId: 'dockerhub-creds', url: 'https://index.docker.io/v2/') {
       def app = docker.build("maplekiyo36110/docker-nodejs-demo:${commit_id}", '.').push()
     }
   }
}
